DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS user;

CREATE TABLE images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  image TEXT NOT NULL
);